import {
  Accessibility,
  Activity,
  Airplay,
  AlarmClock,
  Ambulance,
  Anchor,
  Aperture,
  Archive,
  Armchair,
  Award,
  Axe,
  Baby,
  Backpack,
  Badge,
  Ban,
  Bandage,
  Banknote,
  Barcode,
  Barrel,
  Bath,
  Battery,
  Beaker,
  Bed,
  Beef,
  Beer,
  Bell,
  Bike,
  Binoculars,
  Biohazard,
  Bitcoin,
  Bomb,
  Book,
  Bookmark,
  Bot,
  BottleWine,
  BowArrow,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Cannabis,
  Car,
  Carrot,
  Castle,
  Cat,
  Cctv,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  ChefHat,
  Cherry,
  Church,
  Cigarette,
  CircleDollarSign,
  CirclePercent,
  CircleStar,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Computer,
  ConciergeBell,
  Contact,
  Cookie,
  CookingPot,
  Copy,
  Copyright,
  Cpu,
  CreditCard,
  Crown,
  Crosshair,
  Database,
  Delete,
  Diamond,
  Dices,
  Dog,
  DollarSign,
  Donut,
  DoorOpen,
  Download,
  Drone,
  Droplet,
  Drum,
  Dumbbell,
  Ear,
  Earth,
  Egg,
  Eraser,
  Euro,
  Eye,
  Factory,
  Fan,
  Feather,
  Fence,
  FerrisWheel,
  Film,
  Fingerprint,
  FireExtinguisher,
  Fish,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  Flower,
  Focus,
  Folder,
  Footprints,
  Forklift,
  Fuel,
  Funnel,
  Gamepad,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  Gift,
  Globe,
  Goal,
  Gpu,
  GraduationCap,
  Grape,
  Grid,
  Guitar,
  Hammer,
  HandHeart,
  Handshake,
  HardDrive,
  HatGlasses,
  Headphones,
  Heart,
  HeartPulse,
  Hospital,
  Hotel,
  Hourglass,
  House,
  IdCard,
  Image,
  Inbox,
  Infinity,
  Info,
  Key,
  Keyboard,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  ListTodo,
  Lock,
  LogIn,
  LogOut,
  Magnet,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MemoryStick,
  MessageSquare,
  Mic,
  Microscope,
  Milestone,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Mouse,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  Nut,
  Package,
  Palette,
  Panda,
  Paperclip,
  ParkingMeter,
  PartyPopper,
  Pause,
  PawPrint,
  Pen,
  Pencil,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pin,
  Plane,
  Play,
  Plug,
  Plus,
  Podcast,
  Pointer,
  Popcorn,
  Power,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Radar,
  Radiation,
  Radio,
  Rainbow,
  Receipt,
  Recycle,
  Redo,
  RefreshCw,
  Refrigerator,
  Regex,
  Repeat,
  Reply,
  Rewind,
  Ribbon,
  Rocket,
  Route,
  Router,
  Rss,
  Ruler,
  Satellite,
  Save,
  Scale,
  Scissors,
  ScrollText,
  Search,
  Send,
  Server,
  Settings,
  Shapes,
  Share,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  ShowerHead,
  Shrimp,
  Signal,
  Signature,
  Skull,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  SoapDispenserDroplet,
  Sofa,
  Soup,
  Spade,
  Sparkles,
  Speaker,
  SpellCheck,
  Split,
  SprayCan,
  Sprout,
  SquareStack,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Tag,
  Target,
  Telescope,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  Timer,
  Tornado,
  Tractor,
  TrafficCone,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Upload,
  Usb,
  User,
  Users,
  Utensils,
  Vault,
  Vegan,
  Video,
  Voicemail,
  Wallet,
  WandSparkles,
  Warehouse,
  Watch,
  Waves,
  Webcam,
  Weight,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Zap,
  ZoomIn,
  ZoomOut,
} from '@lucide/svelte'

// prettier-ignore
export const lucideIcons: Record<string, typeof Activity> = {
  "accessibility": Accessibility,
  "activity": Activity,
  "airplay": Airplay,
  "alarm-clock": AlarmClock,
  "ambulance": Ambulance,
  "anchor": Anchor,
  "aperture": Aperture,
  "archive": Archive,
  "armchair": Armchair,
  "award": Award,
  "axe": Axe,
  "baby": Baby,
  "backpack": Backpack,
  "badge": Badge,
  "ban": Ban,
  "bandage": Bandage,
  "banknote": Banknote,
  "barcode": Barcode,
  "barrel": Barrel,
  "bath": Bath,
  "battery": Battery,
  "beaker": Beaker,
  "bed": Bed,
  "beef": Beef,
  "beer": Beer,
  "bell": Bell,
  "bike": Bike,
  "binoculars": Binoculars,
  "biohazard": Biohazard,
  "bitcoin": Bitcoin,
  "bomb": Bomb,
  "book": Book,
  "bookmark": Bookmark,
  "bot": Bot,
  "bottle-wine": BottleWine,
  "bow-arrow": BowArrow,
  "box": Box,
  "brain": Brain,
  "briefcase": Briefcase,
  "brush": Brush,
  "bug": Bug,
  "building": Building,
  "bus": Bus,
  "cake": Cake,
  "calculator": Calculator,
  "calendar": Calendar,
  "camera": Camera,
  "candy": Candy,
  "cannabis": Cannabis,
  "car": Car,
  "carrot": Carrot,
  "castle": Castle,
  "cat": Cat,
  "cctv": Cctv,
  "chart-bar": ChartBar,
  "chart-line": ChartLine,
  "chart-pie": ChartPie,
  "check": Check,
  "chef-hat": ChefHat,
  "cherry": Cherry,
  "church": Church,
  "cigarette": Cigarette,
  "circle-dollar-sign": CircleDollarSign,
  "circle-percent": CirclePercent,
  "circle-star": CircleStar,
  "clipboard": Clipboard,
  "clock": Clock,
  "cloud": Cloud,
  "code": Code,
  "coffee": Coffee,
  "cog": Cog,
  "coins": Coins,
  "compass": Compass,
  "computer": Computer,
  "concierge-bell": ConciergeBell,
  "contact": Contact,
  "cookie": Cookie,
  "cooking-pot": CookingPot,
  "copy": Copy,
  "copyright": Copyright,
  "cpu": Cpu,
  "credit-card": CreditCard,
  "crown": Crown,
  "crosshair": Crosshair,
  "database": Database,
  "delete": Delete,
  "diamond": Diamond,
  "dices": Dices,
  "dog": Dog,
  "dollar-sign": DollarSign,
  "donut": Donut,
  "door-open": DoorOpen,
  "download": Download,
  "drone": Drone,
  "droplet": Droplet,
  "drum": Drum,
  "dumbbell": Dumbbell,
  "ear": Ear,
  "earth": Earth,
  "egg": Egg,
  "eraser": Eraser,
  "euro": Euro,
  "eye": Eye,
  "factory": Factory,
  "fan": Fan,
  "feather": Feather,
  "fence": Fence,
  "ferris-wheel": FerrisWheel,
  "film": Film,
  "fingerprint": Fingerprint,
  "fire-extinguisher": FireExtinguisher,
  "fish": Fish,
  "flag": Flag,
  "flame": Flame,
  "flashlight": Flashlight,
  "flask-conical": FlaskConical,
  "flower": Flower,
  "focus": Focus,
  "folder": Folder,
  "footprints": Footprints,
  "forklift": Forklift,
  "fuel": Fuel,
  "funnel": Funnel,
  "gamepad": Gamepad,
  "gauge": Gauge,
  "gavel": Gavel,
  "gem": Gem,
  "ghost": Ghost,
  "gift": Gift,
  "globe": Globe,
  "goal": Goal,
  "gpu": Gpu,
  "graduation-cap": GraduationCap,
  "grape": Grape,
  "grid": Grid,
  "guitar": Guitar,
  "hammer": Hammer,
  "hand-heart": HandHeart,
  "handshake": Handshake,
  "hard-drive": HardDrive,
  "hat-glasses": HatGlasses,
  "headphones": Headphones,
  "heart": Heart,
  "heart-pulse": HeartPulse,
  "hospital": Hospital,
  "hotel": Hotel,
  "hourglass": Hourglass,
  "house": House,
  "id-card": IdCard,
  "image": Image,
  "inbox": Inbox,
  "infinity": Infinity,
  "info": Info,
  "key": Key,
  "keyboard": Keyboard,
  "lamp": Lamp,
  "landmark": Landmark,
  "languages": Languages,
  "laptop": Laptop,
  "leaf": Leaf,
  "library": Library,
  "life-buoy": LifeBuoy,
  "lightbulb": Lightbulb,
  "link": Link,
  "list": List,
  "list-todo": ListTodo,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "magnet": Magnet,
  "mail": Mail,
  "map": Map,
  "map-pin": MapPin,
  "medal": Medal,
  "megaphone": Megaphone,
  "memory-stick": MemoryStick,
  "message-square": MessageSquare,
  "mic": Mic,
  "microscope": Microscope,
  "milestone": Milestone,
  "milk": Milk,
  "monitor": Monitor,
  "moon": Moon,
  "mountain": Mountain,
  "mouse": Mouse,
  "music": Music,
  "navigation": Navigation,
  "network": Network,
  "newspaper": Newspaper,
  "notebook": Notebook,
  "nut": Nut,
  "package": Package,
  "palette": Palette,
  "panda": Panda,
  "paperclip": Paperclip,
  "parking-meter": ParkingMeter,
  "party-popper": PartyPopper,
  "pause": Pause,
  "paw-print": PawPrint,
  "pen": Pen,
  "pencil": Pencil,
  "percent": Percent,
  "phone": Phone,
  "piggy-bank": PiggyBank,
  "pill": Pill,
  "pin": Pin,
  "plane": Plane,
  "play": Play,
  "plug": Plug,
  "plus": Plus,
  "podcast": Podcast,
  "pointer": Pointer,
  "popcorn": Popcorn,
  "power": Power,
  "printer": Printer,
  "puzzle": Puzzle,
  "qr-code": QrCode,
  "quote": Quote,
  "radar": Radar,
  "radiation": Radiation,
  "radio": Radio,
  "rainbow": Rainbow,
  "receipt": Receipt,
  "recycle": Recycle,
  "redo": Redo,
  "refresh": RefreshCw,
  "refrigerator": Refrigerator,
  "regex": Regex,
  "repeat": Repeat,
  "reply": Reply,
  "rewind": Rewind,
  "ribbon": Ribbon,
  "rocket": Rocket,
  "route": Route,
  "router": Router,
  "rss": Rss,
  "ruler": Ruler,
  "satellite": Satellite,
  "save": Save,
  "scale": Scale,
  "scissors": Scissors,
  "scroll-text": ScrollText,
  "search": Search,
  "send": Send,
  "server": Server,
  "settings": Settings,
  "shapes": Shapes,
  "share": Share,
  "shield": Shield,
  "ship": Ship,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "shovel": Shovel,
  "shower-head": ShowerHead,
  "shrimp": Shrimp,
  "signal": Signal,
  "signature": Signature,
  "skull": Skull,
  "sliders": SlidersHorizontal,
  "smartphone": Smartphone,
  "smile": Smile,
  "snowflake": Snowflake,
  "soap": SoapDispenserDroplet,
  "sofa": Sofa,
  "soup": Soup,
  "spade": Spade,
  "sparkles": Sparkles,
  "speaker": Speaker,
  "spell-check": SpellCheck,
  "split": Split,
  "spray-can": SprayCan,
  "sprout": Sprout,
  "square-stack": SquareStack,
  "star": Star,
  "stethoscope": Stethoscope,
  "sticky-note": StickyNote,
  "store": Store,
  "sun": Sun,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "syringe": Syringe,
  "tag": Tag,
  "target": Target,
  "telescope": Telescope,
  "thermometer": Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "ticket": Ticket,
  "timer": Timer,
  "tornado": Tornado,
  "tractor": Tractor,
  "traffic-cone": TrafficCone,
  "train-front": TrainFront,
  "tram-front": TramFront,
  "trash": Trash2,
  "tree": TreeDeciduous,
  "trophy": Trophy,
  "truck": Truck,
  "tv": Tv,
  "umbrella": Umbrella,
  "upload": Upload,
  "usb": Usb,
  "user": User,
  "users": Users,
  "utensils": Utensils,
  "vault": Vault,
  "vegan": Vegan,
  "video": Video,
  "voicemail": Voicemail,
  "wallet": Wallet,
  "wand": WandSparkles,
  "warehouse": Warehouse,
  "watch": Watch,
  "waves": Waves,
  "webcam": Webcam,
  "weight": Weight,
  "wheat": Wheat,
  "wifi": Wifi,
  "wind": Wind,
  "wine": Wine,
  "workflow": Workflow,
  "wrench": Wrench,
  "zap": Zap,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut
} as const
