/*
 * HACK: We do not want to include all icons in the bundle, as this would increase the bundle size by ~1MB.
 * For now, we just provide a selection of icons.
 * In the future, it would be great to have an option to download all icons or such.
 */

import {
  Activity,
  AlarmClock,
  CircleAlert,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  Bell,
  Book,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CircleCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Copy,
  CreditCard,
  Database,
  Download,
  SquarePenIcon,
  Eye,
  EyeOff,
  File,
  FileText,
  Funnel,
  Flag,
  Folder,
  Globe,
  Grid3x3,
  Heart,
  CircleQuestionMark,
  House,
  Image,
  Info,
  Key,
  Layers,
  Link,
  List,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  Menu,
  MessageSquare,
  Minus,
  Monitor,
  Ellipsis,
  EllipsisVertical,
  MousePointer,
  Music,
  Paperclip,
  Pause,
  Phone,
  Play,
  Plus,
  Power,
  RefreshCw,
  Repeat,
  Save,
  Scissors,
  Search,
  Send,
  Settings,
  Share,
  Shield,
  ShoppingCart,
  SkipBack,
  SkipForward,
  SlidersVertical,
  Smartphone,
  Star,
  Sun,
  Tag,
  Target,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Trash,
  TrendingDown,
  TrendingUp,
  Truck,
  LockOpen,
  Upload,
  User,
  Users,
  Video,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  X,
  Zap,
} from '@lucide/svelte'

// prettier-ignore
export const lucideIcons: Record<string, typeof Activity> = {
  "activity": Activity,
  "alarm-clock": AlarmClock,
  "circle-alert": CircleAlert,
  "archive": Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "at-sign": AtSign,
  "award": Award,
  "bell": Bell,
  "book": Book,
  "bookmark": Bookmark,
  "briefcase": Briefcase,
  "calendar": Calendar,
  "camera": Camera,
  "check": Check,
  "circle-check": CircleCheck,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle": Circle,
  "clock": Clock,
  "cloud": Cloud,
  "code": Code,
  "coffee": Coffee,
  "compass": Compass,
  "copy": Copy,
  "credit-card": CreditCard,
  "database": Database,
  "download": Download,
  "square-pen": SquarePenIcon,
  "eye": Eye,
  "eye-off": EyeOff,
  "file": File,
  "file-text": FileText,
  "funnel": Funnel,
  "flag": Flag,
  "folder": Folder,
  "globe": Globe,
  "grid-3x3": Grid3x3,
  "heart": Heart,
  "circle-question-mark": CircleQuestionMark,
  "house": House,
  "image": Image,
  "info": Info,
  "key": Key,
  "layers": Layers,
  "link": Link,
  "list": List,
  "lock": Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  "mail": Mail,
  "map": Map,
  "menu": Menu,
  "message-square": MessageSquare,
  "minus": Minus,
  "monitor": Monitor,
  "ellipsis": Ellipsis,
  "ellipsis-vertical": EllipsisVertical,
  "mouse-pointer": MousePointer,
  "music": Music,
  "paperclip": Paperclip,
  "pause": Pause,
  "phone": Phone,
  "play": Play,
  "plus": Plus,
  "power": Power,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "save": Save,
  "scissors": Scissors,
  "search": Search,
  "send": Send,
  "settings": Settings,
  "share": Share,
  "shield": Shield,
  "shopping-cart": ShoppingCart,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  "sliders-vertical": SlidersVertical,
  "smartphone": Smartphone,
  "star": Star,
  "sun": Sun,
  "tag": Tag,
  "target": Target,
  "terminal": Terminal,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "trash": Trash,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "truck": Truck,
  "lock-open": LockOpen,
  "upload": Upload,
  "user": User,
  "users": Users,
  "video": Video,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "watch": Watch,
  "wifi": Wifi,
  "x": X,
  "zap": Zap,
} as const;
