import type { SettingsBlueprint } from '$lib/index.js'
import {
  CheckSquareIcon,
  DatabaseIcon,
  EyeOffIcon,
  FolderIcon,
  GlobeIcon,
  GridIcon,
  HashIcon,
  HistoryIcon,
  InfoIcon,
  LayersIcon,
  LayoutIcon,
  RefreshCwIcon,
  SettingsIcon,
  SlidersHorizontalIcon,
  SunMoonIcon,
  ToggleLeftIcon,
  TypeIcon,
  ZapIcon,
  GithubIcon,
  ChevronsDownIcon,
  ChevronsUpIcon,
  ListIcon,
  PencilLineIcon,
  SlidersVerticalIcon,
  SmileIcon,
  TagIcon,
  TextInitialIcon,
  ChartNoAxesGanttIcon,
  CloudSunIcon,
  UserIcon,
  PinIcon,
  BrainIcon,
  KeyIcon,
  XIcon,
  PaletteIcon,
} from '@lucide/svelte'

export const settingsConfig = [
  {
    id: 'attributes',
    type: 'variant-list',
    label: 'Attributes',
    icon: TagIcon,
    typeField: 'type',
    itemLabel: 'Attribute',
    defaultToCopy: {
      '87da052f-5ed2-4199-8689-b819d903c407': {
        label: 'Project',
        icon: 'folder',
        type: 'select',
        options: {
          '12137092-f527-4f65-b642-a0ff7d9bd489': { label: 'Task Track', icon: 'timer', color: '#c061cb' },
          '09cf1ba7-eb85-4f6a-b6c1-0bfebcbcb267': { label: 'Weather PWA', icon: 'sun', color: '#62a0ea' },
          '2e7650a7-66ad-4841-8c98-1ce296f5c4ef': { label: 'Svelte Settings', icon: 'settings', color: '#ffa348' },
        },
      },
      '4164793a-8a75-4467-a2f5-a9bf500cf55b': {
        label: 'With',
        icon: 'user',
        type: 'text',
      },
      '20f3d304-3ad7-48cc-9db6-c7b75da56664': {
        label: 'Focus',
        icon: 'target',
        type: 'ordinal',
        min: 0,
        max: 10,
      },
      'f974244d-d9be-40cc-b570-517a97bf99aa': {
        label: 'Number',
        icon: 'calculator',
        type: 'scalar',
      },
    },
    base: [
      {
        id: 'label',
        label: 'Label',
        type: 'text',
        icon: PencilLineIcon,
      },
      {
        id: 'icon',
        label: 'Icon',
        type: 'icon',
        icon: SmileIcon,
      },
      {
        id: 'color',
        label: 'Color',
        type: 'color',
        icon: PaletteIcon,
      },
    ],
    options: [
      {
        id: 'text',
        label: 'Text',
        icon: TextInitialIcon,
        items: [],
      },
      {
        id: 'scalar',
        label: 'Scalar Number',
        icon: HashIcon,
        items: [],
      },
      {
        id: 'ordinal',
        label: 'Ordinal Number',
        icon: SlidersVerticalIcon,
        items: [
          {
            id: 'min',
            label: 'Minimum',
            icon: ChevronsDownIcon,
            type: 'number',
          },
          {
            id: 'max',
            label: 'Maximum',
            icon: ChevronsUpIcon,
            type: 'number',
          },
        ],
      },
      {
        id: 'select',
        label: 'Select',
        icon: ListIcon,
        items: [
          {
            id: 'options',
            label: 'Options',
            icon: ListIcon,
            type: 'item-list',
            nameProperty: 'label',
            iconProperty: 'icon',
            itemLabel: 'Option',
            inline: true,
            children: [
              {
                id: 'label',
                label: 'Label',
                type: 'text',
                icon: PencilLineIcon,
              },
              {
                id: 'icon',
                label: 'Icon',
                type: 'icon',
                icon: SmileIcon,
              },
              {
                id: 'color',
                label: 'Color',
                type: 'color',
                icon: PaletteIcon,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'primitives',
    label: 'Primitives',
    icon: SettingsIcon,
    type: 'page',
    children: [
      {
        id: 'boolean',
        type: 'boolean',
        label: 'boolean',
        icon: ToggleLeftIcon,
        default: false,
        description: 'Lorem ipsum dolor sit amet, just a loooong description',
      },
      {
        id: 'boolean-group',
        type: 'boolean-group',
        label: 'Boolean Group',
        icon: CheckSquareIcon,
        options: ['email', 'push', 'sms'],
        default: ['email', 'push'],
      },
      {
        id: 'number_step',
        type: 'number',
        label: 'number_step',
        icon: HashIcon,
        unit: '×',
        min: 0.75,
        max: 1.5,
        step: 0.01,
        default: 1,
      },
      {
        id: 'number',
        type: 'number',
        label: 'number',
        icon: DatabaseIcon,
        unit: 'items',
        min: 0,
        max: 10000,
        default: 100,
      },
      {
        id: 'text',
        type: 'text',
        label: 'text',
        icon: TypeIcon,
        placeholder: 'https://api.example.com',
        default: '',
      },

      {
        id: 'action',
        type: 'action',
        label: 'action',
        icon: RefreshCwIcon,
        action: () => {},
        description: 'An action which completes instantly.',
      },
      {
        id: 'value',
        type: 'value',
        label: 'value',
        icon: SunMoonIcon,
        value: 'value',
        url: 'https://weather.kjan.dev',
      },
      {
        id: 'value-url',
        type: 'value',
        label: 'Repo',
        value: 'svelte-settings',
        icon: GithubIcon,
        description: 'A label value pair with an optional url.',
        url: 'https://github.com/kaiser-jan/svelte-settings',
      },
      // {
      // 	id: 'action_disabled',
      // 	type: 'action',
      // 	label: 'action_disabled',
      // 	icon: ZapIcon,
      // 	action: () => enableExperimentalFeatures(),
      // 	disabled: true
      // }
    ],
  },

  {
    id: 'advanced',
    label: 'Advanced',
    icon: SlidersHorizontalIcon,
    type: 'page',
    children: [
      {
        id: 'not-implemented',
        label: 'Not Implemented',
        icon: XIcon,
        type: 'not-implemented',
        description:
          'This setting is already present in the config, but there is not yet a fitting setting type to make it changeable.',
      },
      {
        id: 'select',
        type: 'select',
        label: 'select',
        icon: GlobeIcon,
        options: [
          {
            id: 'en',
            label: 'English',
          },
          {
            id: 'de',
            label: 'German',
          },
        ] as const,
        default: 'en',
      },
      {
        id: 'item-list',
        type: 'item-list',
        label: 'Item List',
        nameProperty: 'label',
        defaultToCopy: {
          '17eff463-93eb-4c84-a1f3-a1db1f359137': {
            label: 'Label',
            icon: 'smile',
          },
        },
        children: [
          {
            id: 'label',
            type: 'text',
            label: 'Label',
          },
        ],
      },
      {
        id: 'list',
        label: 'List',
        description: 'Select multiple options on a subpage.',
        type: 'list',
        icon: ListIcon,
        options: ['feature-a', 'feature-b', 'feature-c'],
        labels: {
          'feature-a': 'Feature A',
          'feature-b': 'Feature B',
          'feature-c': 'Feature C',
        },
        default: ['feature-a', 'feature-c'],
      },
      {
        id: 'list-inline',
        label: 'List inline',
        description: 'Select multiple options inline.',
        type: 'list',
        inline: true,
        icon: ListIcon,
        options: ['feature-a', 'feature-b', 'feature-c'],
        labels: {
          'feature-a': 'Feature A',
          'feature-b': 'Feature B',
          'feature-c': 'Feature C',
        },
        default: ['feature-a', 'feature-c'],
      },
      {
        id: 'changelog',
        type: 'changelog',
        label: 'Changelog',
        icon: HistoryIcon,
        changelog: async () => {
          const module = await import('changelog.json')
          return module.default
        },
      },
    ],
  },

  {
    id: 'layout',
    label: 'Layout',
    icon: LayoutIcon,
    type: 'page',
    children: [
      {
        id: 'description',
        type: 'description',
        label: 'description',
        icon: InfoIcon,
        text: 'Demo: primitives, advanced and layout groups.',
      },
      {
        id: 'group',
        type: 'group',
        label: 'group',
        icon: LayersIcon,
        children: [
          {
            id: 'number_columns',
            type: 'number',
            label: 'number',
            icon: GridIcon,
            min: 1,
            max: 4,
            default: 2,
          },
        ],
      },
      {
        id: 'nested_page',
        type: 'page',
        label: 'nested_page',
        icon: FolderIcon,
        children: [
          {
            id: 'telemetry',
            type: 'boolean',
            label: 'boolean',
            icon: EyeOffIcon,
            default: false,
            description: 'Anonymous usage metrics.',
          },
        ],
      },
    ],
  },
] as const satisfies SettingsBlueprint
